-- AlterTable
ALTER TABLE "Reservation" ALTER COLUMN "DateDebut" DROP NOT NULL,
ALTER COLUMN "DateDebut" SET DATA TYPE TEXT,
ALTER COLUMN "DateFin" DROP NOT NULL,
ALTER COLUMN "DateFin" SET DATA TYPE TEXT;
